# ==================================================================
# Dockerfile para el Entorno de Desarrollo de WayrApp Backend
# ==================================================================

# 1. Imagen Base, esta es la última LTS
FROM node:22.19.0-alpine

# 2. Directorio de Trabajo
# Establecemos el directorio de trabajo dentro del contenedor.
# Todos los comandos siguientes se ejecutarán en este contexto.
WORKDIR /usr/src/app

# 3. Copiar los archivos de configuración y el esquema de Prisma
COPY package*.json ./

# 4. Instalar Dependencias
RUN npm install

# 5. Copiar el resto del código fuente
COPY . .

# 6. Exponer el Puerto
# Informamos a Docker que el contenedor escuchará en el puerto 3000.
# Esto es principalmente para documentación. El mapeo real se hace en docker-compose.yml.
EXPOSE 3000

# 7. Comando de Inicio por Defecto
# Este es el comando que se ejecutará cuando el contenedor inicie.
# Está diseñado para un entorno de desarrollo con hot-reloading.
# Asumimos que tendremos un script "dev" en el package.json.
CMD ["npm", "run", "dev"]